global:
  edition: ce

  hosts:
    domain: gitlab.local
    https: false

  ingress:
    configureCertmanager: false
    class: traefik

installCertmanager: false

nginx-ingress:
  enabled: false

certmanager:
  install: false

prometheus:
  install: false

gitlab-runner:
  install: false

registry:
  enabled: false


gitlab:

  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 400m
        memory: 1.2G
      limits:
        cpu: 900m
        memory: 2.5G

  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 512M
      limits:
        cpu: 300m
        memory: 1G

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128M
      limits:
        cpu: 200m
        memory: 256M
  
  minio:
    enabled: false

  toolbox:
    enabled: true

  kas:
    enabled: false

  gitlab-exporter:
    enabled: false

postgresql:
  install: true
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1Gi

redis:
  install: true
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 512Mi