
global:
  hosts:
    domain: gitlab.local
    externalIP: 127.0.0.1
    https: false

  
  ingress:
    configureCertmanager: false
    class: "traefik"
    
  rails:
    bootsnap:
      enabled: false

installCertmanager: false

nginx-ingress:
  enabled: false

certmanager:
  install: false

prometheus:
  install: false

gitlab-runner:
  install: false

registry:
  install: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1

  sidekiq:
    minReplicas: 1
    maxReplicas: 1

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  kas:
    enable: false
  toolbox:
    enable: false
  gitlab-exporter:
    enable: false
