
Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"

  config.vm.define "maddouS" do |maddouS|
    maddouS.vm.hostname = "maddouS"
    maddouS.vm.network "private_network", ip: "192.168.56.110"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    config.vm.provision "shell", path: "scripts/install_k3s.sh"
  end

end
